package vn.edu.fpt.fts.model;

// Generated Feb 4, 2015 3:30:12 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver implements java.io.Serializable {

	private int driverId;
	private Vehicle vehicle;
	private Serializable email;
	private Serializable firstName;
	private Serializable lastName;
	private Integer sex;
	private Serializable phone;
	private boolean isActive;
	private Serializable createBy;
	private Date createTime;
	private Serializable updateBy;
	private Date updateTime;
	private Integer age;
	private Serializable image;
	private int point;
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Route> routes = new HashSet<Route>(0);

	public Driver() {
	}

	public Driver(int driverId, Serializable email, Serializable phone,
			boolean isActive, Serializable createBy, Date createTime,
			Serializable updateBy, Date updateTime, Serializable image,
			int point) {
		this.driverId = driverId;
		this.email = email;
		this.phone = phone;
		this.isActive = isActive;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.image = image;
		this.point = point;
	}

	public Driver(int driverId, Vehicle vehicle, Serializable email,
			Serializable firstName, Serializable lastName, Integer sex,
			Serializable phone, boolean isActive, Serializable createBy,
			Date createTime, Serializable updateBy, Date updateTime,
			Integer age, Serializable image, int point, Set<Account> accounts,
			Set<Route> routes) {
		this.driverId = driverId;
		this.vehicle = vehicle;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.sex = sex;
		this.phone = phone;
		this.isActive = isActive;
		this.createBy = createBy;
		this.createTime = createTime;
		this.updateBy = updateBy;
		this.updateTime = updateTime;
		this.age = age;
		this.image = image;
		this.point = point;
		this.accounts = accounts;
		this.routes = routes;
	}

	public int getDriverId() {
		return this.driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Serializable getPhone() {
		return this.phone;
	}

	public void setPhone(Serializable phone) {
		this.phone = phone;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Serializable getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Serializable createBy) {
		this.createBy = createBy;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Serializable getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Serializable updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Serializable getImage() {
		return this.image;
	}

	public void setImage(Serializable image) {
		this.image = image;
	}

	public int getPoint() {
		return this.point;
	}

	public void setPoint(int point) {
		this.point = point;
	}

	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	public Set<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set<Route> routes) {
		this.routes = routes;
	}

}
