package vn.edu.fpt.fts.model;

// Generated Feb 4, 2015 3:30:12 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int employeeId;
	private Serializable email;
	private Serializable firstName;
	private Serializable lastName;
	private Serializable phone;
	private int sex;
	private Serializable image;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Employee() {
	}

	public Employee(int employeeId, Serializable email, Serializable phone,
			int sex, Serializable image) {
		this.employeeId = employeeId;
		this.email = email;
		this.phone = phone;
		this.sex = sex;
		this.image = image;
	}

	public Employee(int employeeId, Serializable email, Serializable firstName,
			Serializable lastName, Serializable phone, int sex,
			Serializable image, Set<Account> accounts) {
		this.employeeId = employeeId;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.sex = sex;
		this.image = image;
		this.accounts = accounts;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	public Serializable getPhone() {
		return this.phone;
	}

	public void setPhone(Serializable phone) {
		this.phone = phone;
	}

	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public Serializable getImage() {
		return this.image;
	}

	public void setImage(Serializable image) {
		this.image = image;
	}

	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
