package vn.edu.fpt.fts.model;

import java.sql.Time;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Goods generated by hbm2java
 */
@XmlRootElement
public class Goods implements java.io.Serializable {

	private int GoodsID;
	private int Weight;
	private double Price;
	private Time PickupTime;
	private String PickupAddress;
	private Time DeliveryTime;
	private String DeliveryAddress;
	private float PickupMarkerLongtitude;
	private float PickupMarkerLatidute;
	private float DeliveryMarkerLongtitude;
	private float DeliveryMarkerLatidute;
	private String Notes;
	private Time CreateTime;
	private int Active;
	private int OwnerID;
	private int GoodsCategoryID;
	
	public Goods() {
		// TODO Auto-generated constructor stub
	}

	public Goods(int goodsID, int weight, double price, Time pickupTime,
			String pickupAddress, Time deliveryTime, String deliveryAddress,
			float pickupMarkerLongtitude, float pickupMarkerLatidute,
			float deliveryMarkerLongtitude, float deliveryMarkerLatidute,
			String notes, Time createTime, int active, int ownerID,
			int goodsCategoryID) {
		super();
		GoodsID = goodsID;
		Weight = weight;
		Price = price;
		PickupTime = pickupTime;
		PickupAddress = pickupAddress;
		DeliveryTime = deliveryTime;
		DeliveryAddress = deliveryAddress;
		PickupMarkerLongtitude = pickupMarkerLongtitude;
		PickupMarkerLatidute = pickupMarkerLatidute;
		DeliveryMarkerLongtitude = deliveryMarkerLongtitude;
		DeliveryMarkerLatidute = deliveryMarkerLatidute;
		Notes = notes;
		CreateTime = createTime;
		Active = active;
		OwnerID = ownerID;
		GoodsCategoryID = goodsCategoryID;
	}

	public int getGoodsID() {
		return GoodsID;
	}

	public void setGoodsID(int goodsID) {
		GoodsID = goodsID;
	}

	public int getWeight() {
		return Weight;
	}

	public void setWeight(int weight) {
		Weight = weight;
	}

	public double getPrice() {
		return Price;
	}

	public void setPrice(double price) {
		Price = price;
	}

	public Time getPickupTime() {
		return PickupTime;
	}

	public void setPickupTime(Time pickupTime) {
		PickupTime = pickupTime;
	}

	public String getPickupAddress() {
		return PickupAddress;
	}

	public void setPickupAddress(String pickupAddress) {
		PickupAddress = pickupAddress;
	}

	public Time getDeliveryTime() {
		return DeliveryTime;
	}

	public void setDeliveryTime(Time deliveryTime) {
		DeliveryTime = deliveryTime;
	}

	public String getDeliveryAddress() {
		return DeliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		DeliveryAddress = deliveryAddress;
	}

	public float getPickupMarkerLongtitude() {
		return PickupMarkerLongtitude;
	}

	public void setPickupMarkerLongtitude(float pickupMarkerLongtitude) {
		PickupMarkerLongtitude = pickupMarkerLongtitude;
	}

	public float getPickupMarkerLatidute() {
		return PickupMarkerLatidute;
	}

	public void setPickupMarkerLatidute(float pickupMarkerLatidute) {
		PickupMarkerLatidute = pickupMarkerLatidute;
	}

	public float getDeliveryMarkerLongtitude() {
		return DeliveryMarkerLongtitude;
	}

	public void setDeliveryMarkerLongtitude(float deliveryMarkerLongtitude) {
		DeliveryMarkerLongtitude = deliveryMarkerLongtitude;
	}

	public float getDeliveryMarkerLatidute() {
		return DeliveryMarkerLatidute;
	}

	public void setDeliveryMarkerLatidute(float deliveryMarkerLatidute) {
		DeliveryMarkerLatidute = deliveryMarkerLatidute;
	}

	public String getNotes() {
		return Notes;
	}

	public void setNotes(String notes) {
		Notes = notes;
	}

	public Time getCreateTime() {
		return CreateTime;
	}

	public void setCreateTime(Time createTime) {
		CreateTime = createTime;
	}

	public int getActive() {
		return Active;
	}

	public void setActive(int active) {
		Active = active;
	}

	public int getOwnerID() {
		return OwnerID;
	}

	public void setOwnerID(int ownerID) {
		OwnerID = ownerID;
	}

	public int getGoodsCategoryID() {
		return GoodsCategoryID;
	}

	public void setGoodsCategoryID(int goodsCategoryID) {
		GoodsCategoryID = goodsCategoryID;
	}
	
}
