package vn.edu.fpt.fts.model;

// Generated Feb 4, 2015 3:30:12 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.Date;

/**
 * Notification generated by hbm2java
 */
public class Notification implements java.io.Serializable {

	private int notificationId;
	private Serializable emailFrom;
	private Date emailTo;
	private Serializable message;
	private Serializable status;
	private Serializable createTime;

	public Notification() {
	}

	public Notification(int notificationId, Serializable emailFrom,
			Date emailTo, Serializable message, Serializable createTime) {
		this.notificationId = notificationId;
		this.emailFrom = emailFrom;
		this.emailTo = emailTo;
		this.message = message;
		this.createTime = createTime;
	}

	public Notification(int notificationId, Serializable emailFrom,
			Date emailTo, Serializable message, Serializable status,
			Serializable createTime) {
		this.notificationId = notificationId;
		this.emailFrom = emailFrom;
		this.emailTo = emailTo;
		this.message = message;
		this.status = status;
		this.createTime = createTime;
	}

	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	public Serializable getEmailFrom() {
		return this.emailFrom;
	}

	public void setEmailFrom(Serializable emailFrom) {
		this.emailFrom = emailFrom;
	}

	public Date getEmailTo() {
		return this.emailTo;
	}

	public void setEmailTo(Date emailTo) {
		this.emailTo = emailTo;
	}

	public Serializable getMessage() {
		return this.message;
	}

	public void setMessage(Serializable message) {
		this.message = message;
	}

	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	public Serializable getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Serializable createTime) {
		this.createTime = createTime;
	}

}
