package vn.edu.fpt.fts.model;

// Generated Feb 4, 2015 3:30:12 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private int orderId;
	private PaymentType paymentType;
	private OrderStatus orderStatus;
	private double price;
	private Serializable staffDeliveryStatus;
	private Serializable driverDeliveryStatus;
	private Serializable ownerDeliveryStatus;
	private Date createTime;
	private Set<Deal> deals = new HashSet<Deal>(0);

	public Order() {
	}

	public Order(int orderId, PaymentType paymentType, OrderStatus orderStatus,
			double price, Date createTime) {
		this.orderId = orderId;
		this.paymentType = paymentType;
		this.orderStatus = orderStatus;
		this.price = price;
		this.createTime = createTime;
	}

	public Order(int orderId, PaymentType paymentType, OrderStatus orderStatus,
			double price, Serializable staffDeliveryStatus,
			Serializable driverDeliveryStatus,
			Serializable ownerDeliveryStatus, Date createTime, Set<Deal> deals) {
		this.orderId = orderId;
		this.paymentType = paymentType;
		this.orderStatus = orderStatus;
		this.price = price;
		this.staffDeliveryStatus = staffDeliveryStatus;
		this.driverDeliveryStatus = driverDeliveryStatus;
		this.ownerDeliveryStatus = ownerDeliveryStatus;
		this.createTime = createTime;
		this.deals = deals;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public PaymentType getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(PaymentType paymentType) {
		this.paymentType = paymentType;
	}

	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Serializable getStaffDeliveryStatus() {
		return this.staffDeliveryStatus;
	}

	public void setStaffDeliveryStatus(Serializable staffDeliveryStatus) {
		this.staffDeliveryStatus = staffDeliveryStatus;
	}

	public Serializable getDriverDeliveryStatus() {
		return this.driverDeliveryStatus;
	}

	public void setDriverDeliveryStatus(Serializable driverDeliveryStatus) {
		this.driverDeliveryStatus = driverDeliveryStatus;
	}

	public Serializable getOwnerDeliveryStatus() {
		return this.ownerDeliveryStatus;
	}

	public void setOwnerDeliveryStatus(Serializable ownerDeliveryStatus) {
		this.ownerDeliveryStatus = ownerDeliveryStatus;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Set<Deal> getDeals() {
		return this.deals;
	}

	public void setDeals(Set<Deal> deals) {
		this.deals = deals;
	}

}
