package vn.edu.fpt.fts.model;

// Generated Feb 4, 2015 3:30:12 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private int routeId;
	private Vehicle vehicle;
	private Driver driver;
	private Serializable startingPoint;
	private Serializable marker1;
	private Serializable marker2;
	private Serializable destinationPoint;
	private Serializable startTime;
	private Serializable finishTime;
	private Serializable notes;
	private Serializable createTime;
	private Boolean isActive;
	private Set<Deal> deals = new HashSet<Deal>(0);
	private Set<GoodsCategory> goodsCategories = new HashSet<GoodsCategory>(0);

	public Route() {
	}

	public Route(int routeId, Vehicle vehicle, Serializable startingPoint,
			Serializable destinationPoint, Serializable startTime,
			Serializable finishTime) {
		this.routeId = routeId;
		this.vehicle = vehicle;
		this.startingPoint = startingPoint;
		this.destinationPoint = destinationPoint;
		this.startTime = startTime;
		this.finishTime = finishTime;
	}

	public Route(int routeId, Vehicle vehicle, Driver driver,
			Serializable startingPoint, Serializable marker1,
			Serializable marker2, Serializable destinationPoint,
			Serializable startTime, Serializable finishTime,
			Serializable notes, Serializable createTime, Boolean isActive,
			Set<Deal> deals, Set<GoodsCategory> goodsCategories) {
		this.routeId = routeId;
		this.vehicle = vehicle;
		this.driver = driver;
		this.startingPoint = startingPoint;
		this.marker1 = marker1;
		this.marker2 = marker2;
		this.destinationPoint = destinationPoint;
		this.startTime = startTime;
		this.finishTime = finishTime;
		this.notes = notes;
		this.createTime = createTime;
		this.isActive = isActive;
		this.deals = deals;
		this.goodsCategories = goodsCategories;
	}

	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	public Serializable getStartingPoint() {
		return this.startingPoint;
	}

	public void setStartingPoint(Serializable startingPoint) {
		this.startingPoint = startingPoint;
	}

	public Serializable getMarker1() {
		return this.marker1;
	}

	public void setMarker1(Serializable marker1) {
		this.marker1 = marker1;
	}

	public Serializable getMarker2() {
		return this.marker2;
	}

	public void setMarker2(Serializable marker2) {
		this.marker2 = marker2;
	}

	public Serializable getDestinationPoint() {
		return this.destinationPoint;
	}

	public void setDestinationPoint(Serializable destinationPoint) {
		this.destinationPoint = destinationPoint;
	}

	public Serializable getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Serializable startTime) {
		this.startTime = startTime;
	}

	public Serializable getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Serializable finishTime) {
		this.finishTime = finishTime;
	}

	public Serializable getNotes() {
		return this.notes;
	}

	public void setNotes(Serializable notes) {
		this.notes = notes;
	}

	public Serializable getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Serializable createTime) {
		this.createTime = createTime;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<Deal> getDeals() {
		return this.deals;
	}

	public void setDeals(Set<Deal> deals) {
		this.deals = deals;
	}

	public Set<GoodsCategory> getGoodsCategories() {
		return this.goodsCategories;
	}

	public void setGoodsCategories(Set<GoodsCategory> goodsCategories) {
		this.goodsCategories = goodsCategories;
	}

}
