package vn.edu.fpt.fts.model;

// Generated Feb 4, 2015 3:30:12 PM by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private int vehicleId;
	private Serializable number;
	private Serializable type;
	private Set<Route> routes = new HashSet<Route>(0);
	private Set<Driver> drivers = new HashSet<Driver>(0);

	public Vehicle() {
	}

	public Vehicle(int vehicleId, Serializable number, Serializable type) {
		this.vehicleId = vehicleId;
		this.number = number;
		this.type = type;
	}

	public Vehicle(int vehicleId, Serializable number, Serializable type,
			Set<Route> routes, Set<Driver> drivers) {
		this.vehicleId = vehicleId;
		this.number = number;
		this.type = type;
		this.routes = routes;
		this.drivers = drivers;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Serializable getNumber() {
		return this.number;
	}

	public void setNumber(Serializable number) {
		this.number = number;
	}

	public Serializable getType() {
		return this.type;
	}

	public void setType(Serializable type) {
		this.type = type;
	}

	public Set<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set<Route> routes) {
		this.routes = routes;
	}

	public Set<Driver> getDrivers() {
		return this.drivers;
	}

	public void setDrivers(Set<Driver> drivers) {
		this.drivers = drivers;
	}

}
